spring.application.name= CONFIG-DEV

eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.client.service-url.defaultZone= http://theusername:thepassword@localhost:8761/eureka

spring.security.basic.enabled= true
spring.security.user.name= theusername
spring.security.user.password= thepassword
